export const REQUEST_TICKETS_LOADING = 'REQUEST_TICKETS_LOADING'
export const REQUEST_TICKETS_ERROR = 'REQUEST_TICKETS_ERROR'
export const REQUEST_TICKETS_SUCCESS = 'REQUEST_TICKETS_SUCCESS'

export const REQUEST_PROMOS_LOADING = 'REQUEST_PROMOS_LOADING'
export const REQUEST_PROMOS_ERROR = 'REQUEST_PROMOS_ERROR'
export const REQUEST_PROMOS_SUCCESS = 'REQUEST_PROMOS_SUCCESS'

export const REQUEST_MENUS_LOADING = 'REQUEST_MENUS_LOADING'
export const REQUEST_MENUS_ERROR = 'REQUEST_MENUS_ERROR'
export const REQUEST_MENUS_SUCCESS = 'REQUEST_MENUS_SUCCESS'

export const REQUEST_PRODUCTS_LOADING = 'REQUEST_PRODUCTS_LOADING'
export const REQUEST_PRODUCTS_ERROR = 'REQUEST_PRODUCTS_ERROR'
export const REQUEST_PRODUCTS_SUCCESS = 'REQUEST_PRODUCTS_SUCCESS'

export const REQUEST_USER_LOADING = 'REQUEST_USER_LOADING'
export const REQUEST_USER_ERROR = 'REQUEST_USER_ERROR'
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS'

export const ADD_PRODUCT_TO_SHOP_KART = 'ADD_PRODUCT_TO_SHOP_KART'
export const CLEAR_SHOP_KART = 'CLEAR_SHOP_KART'
export const DELETE_PRODUCT_FROM_SHOP_KART = 'ADD_PRODUCT_TO_SHOP_KART'
