export const MOBILE_SIZE = 'MOBILE_SIZE'
export const DESKTOP_SIZE = 'DESKTOP_SIZE'

export const INPUT_EMAIL = 'INPUT_EMAIL'
export const INPUT_PASSWORD = 'INPUT_PASSWORD'
export const CLEAR_FORM = 'CLEAR_FORM'