import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Tickets from '../UI/organisms/Tickets';
import Menus from '../UI/organisms/Menus';
import Promos from '../UI/organisms/Promos';
import Products from '../UI/organisms/Products';
import ClientOnly from '../components/ClientOnly';
import Shopkart from '../UI/organisms/Shopkart';
import PurchaseOrder from '../UI/organisms/PurchaseOrder';
import Login from '../UI/organisms/Login';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Sun Wu Kong</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ClientOnly> 
        {/* <PurchaseOrder/>            
            <Shopkart/>      
            <Promos /> 
            <Products /> 
            <Menus />*/}
            <Login />
            <Tickets/>
        </ClientOnly>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
