import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ClientOnly from '../components/ClientOnly';
import Login from '../UI/organisms/Login';

export default function Home() {

  return (
    <div className={styles.container}>
      
      <Head>
        <title>Sun Wu Kong</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ClientOnly> 
            <Login/>
        </ClientOnly>
      </main>

    </div>
  )
}
